In [1]:
## imports
import pandas as pd
import numpy as np
import mne
import re
import os

from mne.preprocessing import (
    ICA, 
    create_ecg_epochs, 
    corrmap, 
    create_eog_epochs
)

# mne graphics config
# from PySide6 import QtCore, QtGui, QtWidgets, __version__ 

rawa = None
rawb = None

import datetime
print('IMPORTED MODULES today:', datetime.datetime.now())

# Removed cached function import
import sys
try:
    del sys.modules['rename_events']
except KeyError:
    pass

from rename_events import relabel_events


# setup

# SESSION AND POSNER CODES
session_id='m_11_01'
posner_id ='pos1a'
posner_id_b ='pos1b'

IMPORTED MODULES today: 2023-07-11 09:23:55.218344


In [2]:
%matplotlib qt

# Posner A

In [3]:
# Relabel stim events and load raw data
raw_a = relabel_events(session_id, posner_id)

Data file:  m_11_01/m_11_01_pos1a.vhdr


/Users/babe/src/gla/dissertation/go/rename_events.py:50: RuntimeWarning: No coordinate information found for channels ['ECG']. Setting channel types to misc. To avoid this warning, set channel types explicitly.
  raw = mne.io.read_raw_brainvision(vhdr_file, preload=True, verbose=0)


Used Annotations descriptions: ['New Segment/', 'Stimulus/S 10', 'Stimulus/S 30', 'Stimulus/S 40', 'Stimulus/S 50', 'Stimulus/S 51', 'Stimulus/S 60', 'Stimulus/S 70', 'Stimulus/S 80', 'Stimulus/S101', 'Stimulus/S109']
Found '1a' in file: m_11_01/11_1a_posner_task_2023-05-31_16h18.19.322/11_1a_posner_task_2023-05-31_16h18.19.322.csv
Found '1b' in file: m_11_01/11_1b_posner_task_2023-05-31_17h17.36.037/11_1b_posner_task_2023-05-31_17h17.36.037.csv
********** 1a
Used Annotations descriptions: ['New Segment/', 'Stimulus/S 10', 'Stimulus/S 30', 'Stimulus/S 40', 'Stimulus/S 50', 'Stimulus/S 51', 'Stimulus/S 60', 'Stimulus/S 70', 'Stimulus/S 80', 'Stimulus/S101', 'Stimulus/S109']
len(events) 413
len(validity) 100
# of stim events 100
[    0     0 99999]
[28546     0    10]
[64342     0    40]
[65841     0    80]
[69401     0    50]
[69501     0    51]
[70842     0    40]
[72341     0    80]
[75631     0    50]
[75732     0    51]
[77342     0    40]
[78842     0    70]
[81621     0    50]
[81

/Users/babe/src/gla/dissertation/go/rename_events.py:50: RuntimeWarning: Not setting position of 1 misc channel found in montage:
['ECG']
Consider setting the channel types to be of EEG/sEEG/ECoG/DBS/fNIRS using inst.set_channel_types before calling inst.set_montage, or omit these channels when creating your montage.
  raw = mne.io.read_raw_brainvision(vhdr_file, preload=True, verbose=0)


  [255] Keeping  (2023-05-31 16:28:39.875644+00:00 - 2023-05-31 16:28:39.875644+00:00 -> 482.084 - 482.084)
  [256] Keeping  (2023-05-31 16:28:41.186644+00:00 - 2023-05-31 16:28:41.186644+00:00 -> 483.395 - 483.395)
  [257] Keeping  (2023-05-31 16:28:42.685644+00:00 - 2023-05-31 16:28:42.685644+00:00 -> 484.894 - 484.894)
  [258] Keeping  (2023-05-31 16:28:45.645644+00:00 - 2023-05-31 16:28:45.645644+00:00 -> 487.854 - 487.854)
  [259] Keeping  (2023-05-31 16:28:45.745644+00:00 - 2023-05-31 16:28:45.745644+00:00 -> 487.954 - 487.954)
  [260] Keeping  (2023-05-31 16:28:47.685644+00:00 - 2023-05-31 16:28:47.685644+00:00 -> 489.894 - 489.894)
  [261] Keeping  (2023-05-31 16:28:49.186644+00:00 - 2023-05-31 16:28:49.186644+00:00 -> 491.395 - 491.395)
  [262] Keeping  (2023-05-31 16:28:52.805644+00:00 - 2023-05-31 16:28:52.805644+00:00 -> 495.014 - 495.014)
  [263] Keeping  (2023-05-31 16:28:52.905644+00:00 - 2023-05-31 16:28:52.905644+00:00 -> 495.114 - 495.114)
  [264] Keeping  (2023-05-31

In [4]:
event_map = {'1': 11, '10': 10, '101': 101, '109': 109, '11': 11, '117': 117, '20': 20, '30': 30, '40': 40, '5': 5, '50': 50, '51': 51, '52': 52, '60': 60, '70': 70, '80': 80, '99999': 99999}

# get events and times
events, event_id = mne.events_from_annotations(raw_a, event_map)

e_a = events
# all rows with fixation (code 40)
e_40_a = e_a[e_a[:, 2] == 40]
# all rows with trial end (code 101)
e_101_a = e_a[e_a[:,2]==101]

a_tmin= e_40_a[0][0]/1000
a_tmax= e_101_a[-1][0]/1000

# Crop and make a copy and filter
filt_raw_a = raw_a.crop(tmin=a_tmin, tmax=a_tmax).copy().filter(l_freq=1.0, h_freq=40)

epochs_a = mne.Epochs(filt_raw_a, 
                    e_a, 
                    event_id=None, 
                    tmin=-0.2, 
                    tmax=0.5, 
                    preload=True, 
                    baseline=(None, 0))

Used Annotations descriptions: ['10', '101', '109', '30', '40', '50', '51', '52', '60', '70', '80', '99999']
Filtering raw data in 1 contiguous segment
Setting up band-pass filter from 1 - 40 Hz

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandpass filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower passband edge: 1.00
- Lower transition bandwidth: 1.00 Hz (-6 dB cutoff frequency: 0.50 Hz)
- Upper passband edge: 40.00 Hz
- Upper transition bandwidth: 10.00 Hz (-6 dB cutoff frequency: 45.00 Hz)
- Filter length: 3301 samples (3.301 s)



[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.0s remaining:    0.0s


Not setting metadata
413 matching events found
Setting baseline interval to [-0.2, 0.0] s
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 413 events and 701 original time points ...
4 bad epochs dropped


[Parallel(n_jobs=1)]: Done  63 out of  63 | elapsed:    0.9s finished


In [50]:
raw_a.plot()

Using pyopengl with version 3.1.6


Channels marked as bad:
none
Channels marked as bad:
none


In [5]:
# Fitting ICA
ica = ICA(n_components=len(filt_raw_a.ch_names)-1, max_iter="auto", random_state=999)
ica.fit(filt_raw_a)
ica

Fitting ICA to data using 63 channels (please be patient, this may take a while)
Selecting by number: 63 components
Fitting ICA took 64.6s.


<ICA | raw data decomposition, method: fastica (fit in 90 iterations on 675031 samples), 63 ICA components (63 PCA components available), channel types: eeg, no sources marked for exclusion>

In [ ]:
raw_a.load_data()
ica.plot_sources(raw_a)

Creating RawArray with float64 data, n_channels=63, n_times=675031
    Range : 64342 ... 739372 =     64.342 ...   739.372 secs
Ready.
Using qt as 2D backend.
Using pyopengl with version 3.1.6


    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
337 matching events found
No baseline correction applied
0 projection items activated
    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
337 matching events found
No baseline correction applied
0 projection items activated
    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
337 matching events found
No baseline correction applied
0 projection items activated


In [7]:
print(ica.exclude)

[0]


In [8]:
reconstr_raw = raw_a.copy()
# Apply ica to copy
ica.apply(reconstr_raw)
# Plot
raw_a.plot(title="Raw data")
reconstr_raw.plot(title="ICA applied")

Applying ICA to Raw instance
    Transforming to ICA space (63 components)
    Zeroing out 1 ICA component
    Projecting back using 63 PCA components
Using pyopengl with version 3.1.6
Using pyopengl with version 3.1.6


Channels marked as bad:
none
Channels marked as bad:
none


In [9]:
# Save file
file_name = session_id+'_'+posner_id+'.vhdr'
output_dir='cleaned'

print(file_name)
cur_dir = os.getcwd()
session_dir = os.path.join(cur_dir, output_dir, session_id)
print(session_dir)

if not os.path.exists(session_dir):
   os.makedirs(session_dir)

print("\n**** Saving file to: ", session_dir+'/'+file_name) 
mne.export.export_raw(session_dir+'/'+file_name, reconstr_raw, verbose=1)

m_11_01_pos1a.vhdr
/Users/babe/src/gla/dissertation/go/cleaned/m_11_01

**** Saving file to:  /Users/babe/src/gla/dissertation/go/cleaned/m_11_01/m_11_01_pos1a.vhdr


/Applications/MNE-Python/.mne-python/lib/python3.10/site-packages/pybv/_export.py:61: RuntimeWarning: Encountered data in 'short' format. Converting to float32.
  warn(
/Applications/MNE-Python/.mne-python/lib/python3.10/site-packages/pybv/io.py:690: UserWarning: Encountered unsupported non-voltage units: n/a
Note that the BrainVision format specification supports only µV.
  warn(msg)


In [10]:
!tree {session_dir}

/Users/babe/src/gla/dissertation/go/cleaned/m_11_01
├── m_11_01_pos1a.eeg
├── m_11_01_pos1a.vhdr
└── m_11_01_pos1a.vmrk

1 directory, 3 files


In [11]:
del raw_a
del reconstr_raw
del ica
del filt_raw_a

# Posner B

In [12]:
# Relabel stim events and load raw data
raw_b = relabel_events(session_id, posner_id_b)

Data file:  m_11_01/m_11_01_pos1b.vhdr


/Users/babe/src/gla/dissertation/go/rename_events.py:50: RuntimeWarning: No coordinate information found for channels ['ECG']. Setting channel types to misc. To avoid this warning, set channel types explicitly.
  raw = mne.io.read_raw_brainvision(vhdr_file, preload=True, verbose=0)


Used Annotations descriptions: ['New Segment/', 'Stimulus/S 10', 'Stimulus/S 30', 'Stimulus/S 40', 'Stimulus/S 50', 'Stimulus/S 51', 'Stimulus/S 60', 'Stimulus/S 70', 'Stimulus/S 80', 'Stimulus/S101', 'Stimulus/S109', 'Stimulus/S111']
Found '1a' in file: m_11_01/11_1a_posner_task_2023-05-31_16h18.19.322/11_1a_posner_task_2023-05-31_16h18.19.322.csv
Found '1b' in file: m_11_01/11_1b_posner_task_2023-05-31_17h17.36.037/11_1b_posner_task_2023-05-31_17h17.36.037.csv
********** 1b
Used Annotations descriptions: ['New Segment/', 'Stimulus/S 10', 'Stimulus/S 30', 'Stimulus/S 40', 'Stimulus/S 50', 'Stimulus/S 51', 'Stimulus/S 60', 'Stimulus/S 70', 'Stimulus/S 80', 'Stimulus/S101', 'Stimulus/S109', 'Stimulus/S111']
len(events) 414
len(validity) 100
# of stim events 100
[    0     0 99999]
[62710     0   111]
[62711     0    10]
[71123     0    40]
[72623     0    80]
[76063     0    50]
[76163     0    51]
[77623     0    40]
[79123     0    60]
[82063     0    50]
[82163     0    51]
[84133   

/Users/babe/src/gla/dissertation/go/rename_events.py:50: RuntimeWarning: Not setting position of 1 misc channel found in montage:
['ECG']
Consider setting the channel types to be of EEG/sEEG/ECoG/DBS/fNIRS using inst.set_channel_types before calling inst.set_montage, or omit these channels when creating your montage.
  raw = mne.io.read_raw_brainvision(vhdr_file, preload=True, verbose=0)


  [182] Keeping  (2023-05-31 17:25:54.284337+00:00 - 2023-05-31 17:25:54.284337+00:00 -> 366.545 - 366.545)
  [183] Keeping  (2023-05-31 17:25:57.914337+00:00 - 2023-05-31 17:25:57.914337+00:00 -> 370.175 - 370.175)
  [184] Keeping  (2023-05-31 17:25:58.014337+00:00 - 2023-05-31 17:25:58.014337+00:00 -> 370.275 - 370.275)
  [185] Keeping  (2023-05-31 17:25:59.284337+00:00 - 2023-05-31 17:25:59.284337+00:00 -> 371.545 - 371.545)
  [186] Keeping  (2023-05-31 17:26:00.784337+00:00 - 2023-05-31 17:26:00.784337+00:00 -> 373.045 - 373.045)
  [187] Keeping  (2023-05-31 17:26:04.274337+00:00 - 2023-05-31 17:26:04.274337+00:00 -> 376.535 - 376.535)
  [188] Keeping  (2023-05-31 17:26:04.374337+00:00 - 2023-05-31 17:26:04.374337+00:00 -> 376.635 - 376.635)
  [189] Keeping  (2023-05-31 17:26:05.784337+00:00 - 2023-05-31 17:26:05.784337+00:00 -> 378.045 - 378.045)
  [190] Keeping  (2023-05-31 17:26:07.284337+00:00 - 2023-05-31 17:26:07.284337+00:00 -> 379.545 - 379.545)
  [191] Keeping  (2023-05-31

In [13]:
event_map = {'1': 11, '10': 10, '101': 101, '109': 109, '11': 11, '117': 117, '20': 20, '30': 30, '40': 40, '5': 5, '50': 50, '51': 51, '52': 52, '60': 60, '70': 70, '80': 80, '99999': 99999}

# get events and times
events_b, event_id_b = mne.events_from_annotations(raw_b, event_map)

e_b = events_b
# all rows with fixation (code 40)
e_40_b = e_b[e_b[:, 2] == 40]
# all rows with trial end (code 101)
e_101_b = e_b[e_b[:,2]==101]

b_tmin= e_40_b[0][0]/1000
b_tmax= e_101_b[-1][0]/1000

# Crop and make a copy and filter
filt_raw_b = raw_b.crop(tmin=b_tmin, tmax=b_tmax).copy().filter(l_freq=1.0, h_freq=40)

epochs_b = mne.Epochs(filt_raw_b, 
                    e_b, 
                    event_id=None, 
                    tmin=-0.2, 
                    tmax=0.5, 
                    preload=True, 
                    baseline=(None, 0))

Used Annotations descriptions: ['10', '101', '109', '30', '40', '50', '51', '52', '60', '70', '80', '99999']
Filtering raw data in 1 contiguous segment
Setting up band-pass filter from 1 - 40 Hz

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandpass filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower passband edge: 1.00
- Lower transition bandwidth: 1.00 Hz (-6 dB cutoff frequency: 0.50 Hz)
- Upper passband edge: 40.00 Hz
- Upper transition bandwidth: 10.00 Hz (-6 dB cutoff frequency: 45.00 Hz)
- Filter length: 3301 samples (3.301 s)



[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.1s remaining:    0.0s


Not setting metadata
413 matching events found
Setting baseline interval to [-0.2, 0.0] s
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 413 events and 701 original time points ...


[Parallel(n_jobs=1)]: Done  63 out of  63 | elapsed:    0.9s finished


4 bad epochs dropped


In [5]:
raw_b.plot()

Using qt as 2D backend.
Using pyopengl with version 3.1.6


Channels marked as bad:
none


In [14]:
# Fitting ICA
ica_b = ICA(n_components=len(filt_raw_b.ch_names)-1, max_iter="auto", random_state=999)
ica_b.fit(filt_raw_b, verbose='DEBUG')
ica_b

Fitting ICA to data using 63 channels (please be patient, this may take a while)
Selecting by number: 63 components
Cropping annotations 2023-05-31 17:20:58.862337+00:00 - 2023-05-31 17:32:24.104337+00:00
  [0] Keeping  (2023-05-31 17:20:58.862337+00:00 - 2023-05-31 17:20:58.862337+00:00 -> 71.123 - 71.123)
  [1] Keeping  (2023-05-31 17:21:00.362337+00:00 - 2023-05-31 17:21:00.362337+00:00 -> 72.623 - 72.623)
  [2] Keeping  (2023-05-31 17:21:03.802337+00:00 - 2023-05-31 17:21:03.802337+00:00 -> 76.063 - 76.063)
  [3] Keeping  (2023-05-31 17:21:03.902337+00:00 - 2023-05-31 17:21:03.902337+00:00 -> 76.163 - 76.163)
  [4] Keeping  (2023-05-31 17:21:05.362337+00:00 - 2023-05-31 17:21:05.362337+00:00 -> 77.623 - 77.623)
  [5] Keeping  (2023-05-31 17:21:06.862337+00:00 - 2023-05-31 17:21:06.862337+00:00 -> 79.123 - 79.123)
  [6] Keeping  (2023-05-31 17:21:09.802337+00:00 - 2023-05-31 17:21:09.802337+00:00 -> 82.063 - 82.063)
  [7] Keeping  (2023-05-31 17:21:09.902337+00:00 - 2023-05-31 17:21

<ICA | raw data decomposition, method: fastica (fit in 110 iterations on 685242 samples), 63 ICA components (63 PCA components available), channel types: eeg, no sources marked for exclusion>

In [ ]:
raw_b.load_data()
ica_b.plot_sources(raw_b)

Creating RawArray with float64 data, n_channels=63, n_times=685242
    Range : 71123 ... 756364 =     71.123 ...   756.364 secs
Ready.
Using pyopengl with version 3.1.6


    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
342 matching events found
No baseline correction applied
0 projection items activated
    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
342 matching events found
No baseline correction applied
0 projection items activated
    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
342 matching events found
No baseline correction applied
0 projection items activated
    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
342 matching events found
No baseline correction applied
0 projection items activated
    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
342 matching events found
No baseline correction applied
0 projection items activated
    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
342 matching events found
No baseline correction applied
0 projection items ac

In [16]:
ica_b.exclude

[0, 1, 2, 3]

In [17]:
reconstr_raw_b = raw_b.copy()
# Apply ica to copy
ica_b.apply(reconstr_raw_b)
# Plot and compare
raw_b.plot(title="Raw data (posner b)")
reconstr_raw_b.plot(title="ICA applied (posner b)")

Applying ICA to Raw instance
    Transforming to ICA space (63 components)
    Zeroing out 4 ICA components
    Projecting back using 63 PCA components
Using pyopengl with version 3.1.6
Using pyopengl with version 3.1.6


Channels marked as bad:
none
Channels marked as bad:
none


In [18]:
# Save file
file_name_b = session_id+'_'+posner_id_b+'.vhdr'
output_dir_b='cleaned'
cur_dir = os.getcwd()
session_dir = os.path.join(cur_dir, output_dir_b, session_id)
if not os.path.exists(session_dir):
   os.makedirs(session_dir)

print("\n**** Saving file to: ", session_dir+'/'+file_name_b) 
mne.export.export_raw(session_dir+'/'+file_name_b, reconstr_raw_b, verbose=1)


**** Saving file to:  /Users/babe/src/gla/dissertation/go/cleaned/m_11_01/m_11_01_pos1b.vhdr


/Applications/MNE-Python/.mne-python/lib/python3.10/site-packages/pybv/_export.py:61: RuntimeWarning: Encountered data in 'short' format. Converting to float32.
  warn(
/Applications/MNE-Python/.mne-python/lib/python3.10/site-packages/pybv/io.py:690: UserWarning: Encountered unsupported non-voltage units: n/a
Note that the BrainVision format specification supports only µV.
  warn(msg)


In [19]:
!tree {session_dir}

/Users/babe/src/gla/dissertation/go/cleaned/m_11_01
├── m_11_01_pos1a.eeg
├── m_11_01_pos1a.vhdr
├── m_11_01_pos1a.vmrk
├── m_11_01_pos1b.eeg
├── m_11_01_pos1b.vhdr
└── m_11_01_pos1b.vmrk

1 directory, 6 files


# ...

In [20]:
del raw_b
del reconstr_raw_b
del ica_b
del filt_raw_b