In [1]:
## imports
import pandas as pd
import numpy as np
import mne
import re
import os

from mne.preprocessing import (
    ICA, 
    create_ecg_epochs, 
    corrmap, 
    create_eog_epochs
)

# mne graphics config
# from PySide6 import QtCore, QtGui, QtWidgets, __version__ 

rawa = None
rawb = None

import datetime
print('IMPORTED MODULES today:', datetime.datetime.now())

# Removed cached function import
import sys
try:
    del sys.modules['rename_events']
except KeyError:
    pass

from rename_events import relabel_events


# setup

# SESSION AND POSNER CODES
session_id='m_19_01'
posner_id ='pos1a'
posner_id_b ='pos1b'

IMPORTED MODULES today: 2023-07-11 13:25:53.035352


In [2]:
%matplotlib qt

# Posner A

In [3]:
# Relabel stim events and load raw data
raw_a = relabel_events(session_id, posner_id)

Data file:  m_19_01/m_19_01_pos1a.vhdr


/Users/babe/src/gla/dissertation/go/rename_events.py:50: RuntimeWarning: No coordinate information found for channels ['ECG']. Setting channel types to misc. To avoid this warning, set channel types explicitly.
  raw = mne.io.read_raw_brainvision(vhdr_file, preload=True, verbose=0)


Used Annotations descriptions: ['New Segment/', 'Stimulus/S 10', 'Stimulus/S 30', 'Stimulus/S 40', 'Stimulus/S 50', 'Stimulus/S 51', 'Stimulus/S 60', 'Stimulus/S 70', 'Stimulus/S 80', 'Stimulus/S101', 'Stimulus/S109']
Found '1a' in file: m_19_01/19_1a_posner_task_2023-06-20_12h03.13.177/19_1a_posner_task_2023-06-20_12h03.13.177.csv
Found '1b' in file: m_19_01/19_1b_posner_task_2023-06-20_12h59.21.031/19_1b_posner_task_2023-06-20_12h59.21.031.csv
********** 1a
Used Annotations descriptions: ['New Segment/', 'Stimulus/S 10', 'Stimulus/S 30', 'Stimulus/S 40', 'Stimulus/S 50', 'Stimulus/S 51', 'Stimulus/S 60', 'Stimulus/S 70', 'Stimulus/S 80', 'Stimulus/S101', 'Stimulus/S109']
len(events) 411
len(validity) 100
# of stim events 100
[    0     0 99999]
[61515     0    10]
[95602     0    40]
[97101     0    70]
[100132      0     50]
[100231      0     51]
[102102      0     40]
[103602      0     80]
[107112      0     50]
[107212      0     51]
[108602      0     40]
[110102      0     60]

/Users/babe/src/gla/dissertation/go/rename_events.py:50: RuntimeWarning: Not setting position of 1 misc channel found in montage:
['ECG']
Consider setting the channel types to be of EEG/sEEG/ECoG/DBS/fNIRS using inst.set_channel_types before calling inst.set_montage, or omit these channels when creating your montage.
  raw = mne.io.read_raw_brainvision(vhdr_file, preload=True, verbose=0)


  [342] Keeping  (2023-06-20 12:18:14.413235+00:00 - 2023-06-20 12:18:14.413235+00:00 -> 759.686 - 759.686)
  [343] Keeping  (2023-06-20 12:18:15.913235+00:00 - 2023-06-20 12:18:15.913235+00:00 -> 761.186 - 761.186)
  [344] Keeping  (2023-06-20 12:18:19.532235+00:00 - 2023-06-20 12:18:19.532235+00:00 -> 764.805 - 764.805)
  [345] Keeping  (2023-06-20 12:18:19.633235+00:00 - 2023-06-20 12:18:19.633235+00:00 -> 764.906 - 764.906)
  [346] Keeping  (2023-06-20 12:18:20.913235+00:00 - 2023-06-20 12:18:20.913235+00:00 -> 766.186 - 766.186)
  [347] Keeping  (2023-06-20 12:18:22.413235+00:00 - 2023-06-20 12:18:22.413235+00:00 -> 767.686 - 767.686)
  [348] Keeping  (2023-06-20 12:18:25.813235+00:00 - 2023-06-20 12:18:25.813235+00:00 -> 771.086 - 771.086)
  [349] Keeping  (2023-06-20 12:18:25.913235+00:00 - 2023-06-20 12:18:25.913235+00:00 -> 771.186 - 771.186)
  [350] Keeping  (2023-06-20 12:18:27.413235+00:00 - 2023-06-20 12:18:27.413235+00:00 -> 772.686 - 772.686)
  [351] Keeping  (2023-06-20

In [5]:
event_map = {'1': 11, '10': 10, '101': 101, '109': 109, '11': 11, '117': 117, '20': 20, '30': 30, '40': 40, '5': 5, '50': 50, '51': 51, '52': 52, '60': 60, '70': 70, '80': 80, '99999': 99999}

# get events and times
events, event_id = mne.events_from_annotations(raw_a, event_map)

e_a = events
# all rows with fixation (code 40)
e_40_a = e_a[e_a[:, 2] == 40]
# all rows with trial end (code 101)
e_101_a = e_a[e_a[:,2]==101]

a_tmin= e_40_a[0][0]/1000
a_tmax= e_101_a[-1][0]/1000

# Crop and make a copy and filter
filt_raw_a = raw_a.crop(tmin=a_tmin, tmax=a_tmax).copy().filter(l_freq=1.0, h_freq=40)

epochs_a = mne.Epochs(filt_raw_a, 
                    e_a, 
                    event_id=None, 
                    tmin=-0.2, 
                    tmax=0.5, 
                    preload=True, 
                    baseline=(None, 0))

Used Annotations descriptions: ['101', '109', '30', '40', '50', '51', '52', '60', '70', '80']


ValueError: tmax (701.181) must be less than or equal to the max time (605.5790 s)

In [50]:
raw_a.plot()

Using pyopengl with version 3.1.6


Channels marked as bad:
none
Channels marked as bad:
none


In [6]:
# Fitting ICA
ica = ICA(n_components=len(filt_raw_a.ch_names)-1, max_iter="auto", random_state=999)
ica.fit(filt_raw_a)
ica

Fitting ICA to data using 63 channels (please be patient, this may take a while)


Selecting by number: 63 components
Fitting ICA took 56.7s.


<ICA | raw data decomposition, method: fastica (fit in 101 iterations on 605580 samples), 63 ICA components (63 PCA components available), channel types: eeg, no sources marked for exclusion>

In [8]:
raw_a.load_data()
ica.plot_sources(raw_a)

Creating RawArray with float64 data, n_channels=63, n_times=605580
    Range : 95602 ... 701181 =     95.602 ...   701.181 secs
Ready.
Using pyopengl with version 3.1.6


In [9]:
print(ica.exclude)

[0, 1]


In [10]:
reconstr_raw = raw_a.copy()
# Apply ica to copy
ica.apply(reconstr_raw)
# Plot
raw_a.plot(title="Raw data")
reconstr_raw.plot(title="ICA applied")

Applying ICA to Raw instance
    Transforming to ICA space (63 components)
    Zeroing out 2 ICA components
    Projecting back using 63 PCA components
Using pyopengl with version 3.1.6
Using pyopengl with version 3.1.6


Channels marked as bad:
none
Channels marked as bad:
none


In [11]:
# Save file
file_name = session_id+'_'+posner_id+'.vhdr'
output_dir='cleaned'

print(file_name)
cur_dir = os.getcwd()
session_dir = os.path.join(cur_dir, output_dir, session_id)
print(session_dir)

if not os.path.exists(session_dir):
   os.makedirs(session_dir)

print("\n**** Saving file to: ", session_dir+'/'+file_name) 
mne.export.export_raw(session_dir+'/'+file_name, reconstr_raw, verbose=1)

m_19_01_pos1a.vhdr
/Users/babe/src/gla/dissertation/go/cleaned/m_19_01

**** Saving file to:  /Users/babe/src/gla/dissertation/go/cleaned/m_19_01/m_19_01_pos1a.vhdr


/Applications/MNE-Python/.mne-python/lib/python3.10/site-packages/pybv/_export.py:61: RuntimeWarning: Encountered data in 'short' format. Converting to float32.
  warn(
/Applications/MNE-Python/.mne-python/lib/python3.10/site-packages/pybv/io.py:690: UserWarning: Encountered unsupported non-voltage units: n/a
Note that the BrainVision format specification supports only µV.
  warn(msg)


In [12]:
!tree {session_dir}

/Users/babe/src/gla/dissertation/go/cleaned/m_19_01
├── m_19_01_pos1a.eeg
├── m_19_01_pos1a.vhdr
└── m_19_01_pos1a.vmrk

1 directory, 3 files


In [13]:
del raw_a
del reconstr_raw
del ica
del filt_raw_a

In [52]:
### TESTING ###
# test = mne.io.read_raw_brainvision(session_dir+'/'+file_name, preload=True)

In [53]:
# test.plot()

# Posner B

In [14]:
# Relabel stim events and load raw data
raw_b = relabel_events(session_id, posner_id_b)

Data file:  m_19_01/m_19_01_pos1b.vhdr


/Users/babe/src/gla/dissertation/go/rename_events.py:50: RuntimeWarning: No coordinate information found for channels ['ECG']. Setting channel types to misc. To avoid this warning, set channel types explicitly.
  raw = mne.io.read_raw_brainvision(vhdr_file, preload=True, verbose=0)


Used Annotations descriptions: ['New Segment/', 'Stimulus/S 10', 'Stimulus/S 30', 'Stimulus/S 40', 'Stimulus/S 50', 'Stimulus/S 51', 'Stimulus/S 60', 'Stimulus/S 70', 'Stimulus/S 80', 'Stimulus/S101', 'Stimulus/S109']
Found '1a' in file: m_19_01/19_1a_posner_task_2023-06-20_12h03.13.177/19_1a_posner_task_2023-06-20_12h03.13.177.csv
Found '1b' in file: m_19_01/19_1b_posner_task_2023-06-20_12h59.21.031/19_1b_posner_task_2023-06-20_12h59.21.031.csv
********** 1b
Used Annotations descriptions: ['New Segment/', 'Stimulus/S 10', 'Stimulus/S 30', 'Stimulus/S 40', 'Stimulus/S 50', 'Stimulus/S 51', 'Stimulus/S 60', 'Stimulus/S 70', 'Stimulus/S 80', 'Stimulus/S101', 'Stimulus/S109']
len(events) 413
len(validity) 100
# of stim events 100
[    0     0 99999]
[108108      0     10]
[141032      0     40]
[142532      0     60]
[145032      0     50]
[145132      0     51]
[147532      0     40]
[149032      0     70]
[152122      0     50]
[152222      0     51]
[154042      0     40]
[155542      

/Users/babe/src/gla/dissertation/go/rename_events.py:50: RuntimeWarning: Not setting position of 1 misc channel found in montage:
['ECG']
Consider setting the channel types to be of EEG/sEEG/ECoG/DBS/fNIRS using inst.set_channel_types before calling inst.set_montage, or omit these channels when creating your montage.
  raw = mne.io.read_raw_brainvision(vhdr_file, preload=True, verbose=0)


  [306] Keeping  (2023-06-20 13:13:14.177458+00:00 - 2023-06-20 13:13:14.177458+00:00 -> 693.425 - 693.425)
  [307] Keeping  (2023-06-20 13:13:14.277458+00:00 - 2023-06-20 13:13:14.277458+00:00 -> 693.525 - 693.525)
  [308] Keeping  (2023-06-20 13:13:16.630458+00:00 - 2023-06-20 13:13:16.630458+00:00 -> 695.878 - 695.878)
  [309] Keeping  (2023-06-20 13:13:25.393458+00:00 - 2023-06-20 13:13:25.393458+00:00 -> 704.641 - 704.641)
  [310] Keeping  (2023-06-20 13:13:33.332458+00:00 - 2023-06-20 13:13:33.332458+00:00 -> 712.58 - 712.58)
  [311] Keeping  (2023-06-20 13:13:33.333458+00:00 - 2023-06-20 13:13:33.333458+00:00 -> 712.581 - 712.581)
  [312] Keeping  (2023-06-20 13:13:34.837458+00:00 - 2023-06-20 13:13:34.837458+00:00 -> 714.085 - 714.085)
  [313] Keeping  (2023-06-20 13:13:38.437458+00:00 - 2023-06-20 13:13:38.437458+00:00 -> 717.685 - 717.685)
  [314] Keeping  (2023-06-20 13:13:38.537458+00:00 - 2023-06-20 13:13:38.537458+00:00 -> 717.785 - 717.785)
  [315] Keeping  (2023-06-20 1

In [15]:
event_map = {'1': 11, '10': 10, '101': 101, '109': 109, '11': 11, '117': 117, '20': 20, '30': 30, '40': 40, '5': 5, '50': 50, '51': 51, '52': 52, '60': 60, '70': 70, '80': 80, '99999': 99999}

# get events and times
events_b, event_id_b = mne.events_from_annotations(raw_b, event_map)

e_b = events_b
# all rows with fixation (code 40)
e_40_b = e_b[e_b[:, 2] == 40]
# all rows with trial end (code 101)
e_101_b = e_b[e_b[:,2]==101]

b_tmin= e_40_b[0][0]/1000
b_tmax= e_101_b[-1][0]/1000

# Crop and make a copy and filter
filt_raw_b = raw_b.crop(tmin=b_tmin, tmax=b_tmax).copy().filter(l_freq=1.0, h_freq=40)

epochs_b = mne.Epochs(filt_raw_b, 
                    e_b, 
                    event_id=None, 
                    tmin=-0.2, 
                    tmax=0.5, 
                    preload=True, 
                    baseline=(None, 0))

Used Annotations descriptions: ['10', '101', '109', '30', '40', '50', '51', '52', '60', '70', '80', '99999']
Filtering raw data in 1 contiguous segment
Setting up band-pass filter from 1 - 40 Hz

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandpass filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower passband edge: 1.00
- Lower transition bandwidth: 1.00 Hz (-6 dB cutoff frequency: 0.50 Hz)
- Upper passband edge: 40.00 Hz
- Upper transition bandwidth: 10.00 Hz (-6 dB cutoff frequency: 45.00 Hz)
- Filter length: 3301 samples (3.301 s)



[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.1s remaining:    0.0s


Not setting metadata
413 matching events found
Setting baseline interval to [-0.2, 0.0] s
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 413 events and 701 original time points ...
4 bad epochs dropped


[Parallel(n_jobs=1)]: Done  63 out of  63 | elapsed:    0.7s finished


In [5]:
raw_b.plot()

Using qt as 2D backend.
Using pyopengl with version 3.1.6


Channels marked as bad:
none


In [16]:
# Fitting ICA
ica_b = ICA(n_components=len(filt_raw_b.ch_names)-1, max_iter="auto", random_state=999)
ica_b.fit(filt_raw_b, verbose='DEBUG')
ica_b

Fitting ICA to data using 63 channels (please be patient, this may take a while)
Selecting by number: 63 components
Cropping annotations 2023-06-20 13:04:01.784458+00:00 - 2023-06-20 13:16:18.155458+00:00
  [0] Keeping  (2023-06-20 13:04:01.784458+00:00 - 2023-06-20 13:04:01.784458+00:00 -> 141.032 - 141.032)
  [1] Keeping  (2023-06-20 13:04:03.284458+00:00 - 2023-06-20 13:04:03.284458+00:00 -> 142.532 - 142.532)
  [2] Keeping  (2023-06-20 13:04:05.784458+00:00 - 2023-06-20 13:04:05.784458+00:00 -> 145.032 - 145.032)
  [3] Keeping  (2023-06-20 13:04:05.884458+00:00 - 2023-06-20 13:04:05.884458+00:00 -> 145.132 - 145.132)
  [4] Keeping  (2023-06-20 13:04:08.284458+00:00 - 2023-06-20 13:04:08.284458+00:00 -> 147.532 - 147.532)
  [5] Keeping  (2023-06-20 13:04:09.784458+00:00 - 2023-06-20 13:04:09.784458+00:00 -> 149.032 - 149.032)
  [6] Keeping  (2023-06-20 13:04:12.874458+00:00 - 2023-06-20 13:04:12.874458+00:00 -> 152.122 - 152.122)
  [7] Keeping  (2023-06-20 13:04:12.974458+00:00 - 20

<ICA | raw data decomposition, method: fastica (fit in 69 iterations on 736371 samples), 63 ICA components (63 PCA components available), channel types: eeg, no sources marked for exclusion>

In [ ]:
raw_b.load_data()
ica_b.plot_sources(raw_b)

Creating RawArray with float64 data, n_channels=63, n_times=736371
    Range : 141032 ... 877402 =    141.032 ...   877.402 secs
Ready.
Using pyopengl with version 3.1.6


    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
368 matching events found
No baseline correction applied
0 projection items activated
    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
368 matching events found
No baseline correction applied
0 projection items activated
    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
368 matching events found
No baseline correction applied
0 projection items activated
    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
368 matching events found
No baseline correction applied
0 projection items activated


In [18]:
ica_b.exclude

[0, 2]

In [19]:
reconstr_raw_b = raw_b.copy()
# Apply ica to copy
ica_b.apply(reconstr_raw_b)
# Plot and compare
raw_b.plot(title="Raw data (posner b)")
reconstr_raw_b.plot(title="ICA applied (posner b)")

Applying ICA to Raw instance
    Transforming to ICA space (63 components)
    Zeroing out 2 ICA components
    Projecting back using 63 PCA components
Using pyopengl with version 3.1.6
Using pyopengl with version 3.1.6


Channels marked as bad:
none
Channels marked as bad:
none


In [20]:
# Save file
file_name_b = session_id+'_'+posner_id_b+'.vhdr'
output_dir_b='cleaned'
cur_dir = os.getcwd()
session_dir = os.path.join(cur_dir, output_dir_b, session_id)
if not os.path.exists(session_dir):
   os.makedirs(session_dir)

print("\n**** Saving file to: ", session_dir+'/'+file_name_b) 
mne.export.export_raw(session_dir+'/'+file_name_b, reconstr_raw_b, verbose=1)


**** Saving file to:  /Users/babe/src/gla/dissertation/go/cleaned/m_19_01/m_19_01_pos1b.vhdr


/Applications/MNE-Python/.mne-python/lib/python3.10/site-packages/pybv/_export.py:61: RuntimeWarning: Encountered data in 'short' format. Converting to float32.
  warn(
/Applications/MNE-Python/.mne-python/lib/python3.10/site-packages/pybv/io.py:690: UserWarning: Encountered unsupported non-voltage units: n/a
Note that the BrainVision format specification supports only µV.
  warn(msg)


In [21]:
!tree {session_dir}

/Users/babe/src/gla/dissertation/go/cleaned/m_19_01
├── m_19_01_pos1a.eeg
├── m_19_01_pos1a.vhdr
├── m_19_01_pos1a.vmrk
├── m_19_01_pos1b.eeg
├── m_19_01_pos1b.vhdr
└── m_19_01_pos1b.vmrk

1 directory, 6 files


# ...

In [22]:
del raw_b
del reconstr_raw_b
del ica_b
del filt_raw_b