In [1]:
## imports
import pandas as pd
import numpy as np
import mne
import re
import os

from mne.preprocessing import (
    ICA, 
    create_ecg_epochs, 
    corrmap, 
    create_eog_epochs
)

# mne graphics config
# from PySide6 import QtCore, QtGui, QtWidgets, __version__ 

rawa = None
rawb = None

import datetime
print('IMPORTED MODULES today:', datetime.datetime.now())

# Removed cached function import
import sys
try:
    del sys.modules['rename_events']
except KeyError:
    pass

from rename_events import relabel_events


# setup

# SESSION AND POSNER CODES
session_id='m_15_01'
posner_id ='pos1a'
posner_id_b ='pos1b'

IMPORTED MODULES today: 2023-07-11 10:21:40.805034


In [2]:
%matplotlib qt

# Posner A

In [3]:
# Relabel stim events and load raw data
raw_a = relabel_events(session_id, posner_id)

Data file:  m_15_01/m_15_01_pos1a.vhdr


/Users/babe/src/gla/dissertation/go/rename_events.py:50: RuntimeWarning: No coordinate information found for channels ['ECG']. Setting channel types to misc. To avoid this warning, set channel types explicitly.
  raw = mne.io.read_raw_brainvision(vhdr_file, preload=True, verbose=0)


Used Annotations descriptions: ['New Segment/', 'Stimulus/S 10', 'Stimulus/S 20', 'Stimulus/S 30', 'Stimulus/S 40', 'Stimulus/S 50', 'Stimulus/S 51', 'Stimulus/S 60', 'Stimulus/S 70', 'Stimulus/S 80', 'Stimulus/S101', 'Stimulus/S109', 'Stimulus/S117']
Found '1a' in file: m_15_01/15_1a_posner_task_2023-06-07_18h43.06.180/15_1a_posner_task_2023-06-07_18h43.06.180.csv
Found '1b' in file: m_15_01/15_1b_posner_task_2023-06-07_19h41.14.289/15_1b_posner_task_2023-06-07_19h41.14.289.csv
********** 1a
Used Annotations descriptions: ['New Segment/', 'Stimulus/S 10', 'Stimulus/S 20', 'Stimulus/S 30', 'Stimulus/S 40', 'Stimulus/S 50', 'Stimulus/S 51', 'Stimulus/S 60', 'Stimulus/S 70', 'Stimulus/S 80', 'Stimulus/S101', 'Stimulus/S109', 'Stimulus/S117']
len(events) 415
len(validity) 100
# of stim events 100
[    0     0 99999]
[32046     0    10]
[40320     0    40]
[41820     0    60]
[44390     0    50]
[44490     0    51]
[46830     0    40]
[48330     0    60]
[51210     0    50]
[51310     0   

/Users/babe/src/gla/dissertation/go/rename_events.py:50: RuntimeWarning: Not setting position of 1 misc channel found in montage:
['ECG']
Consider setting the channel types to be of EEG/sEEG/ECoG/DBS/fNIRS using inst.set_channel_types before calling inst.set_montage, or omit these channels when creating your montage.
  raw = mne.io.read_raw_brainvision(vhdr_file, preload=True, verbose=0)


  [288] Keeping  (2023-06-07 18:53:13.319758+00:00 - 2023-06-07 18:53:13.319758+00:00 -> 516.753 - 516.753)
  [289] Keeping  (2023-06-07 18:53:14.819758+00:00 - 2023-06-07 18:53:14.819758+00:00 -> 518.253 - 518.253)
  [290] Keeping  (2023-06-07 18:53:17.849758+00:00 - 2023-06-07 18:53:17.849758+00:00 -> 521.283 - 521.283)
  [291] Keeping  (2023-06-07 18:53:17.949758+00:00 - 2023-06-07 18:53:17.949758+00:00 -> 521.383 - 521.383)
  [292] Keeping  (2023-06-07 18:53:19.819758+00:00 - 2023-06-07 18:53:19.819758+00:00 -> 523.253 - 523.253)
  [293] Keeping  (2023-06-07 18:53:21.319758+00:00 - 2023-06-07 18:53:21.319758+00:00 -> 524.753 - 524.753)
  [294] Keeping  (2023-06-07 18:53:24.459758+00:00 - 2023-06-07 18:53:24.459758+00:00 -> 527.893 - 527.893)
  [295] Keeping  (2023-06-07 18:53:24.559758+00:00 - 2023-06-07 18:53:24.559758+00:00 -> 527.993 - 527.993)
  [296] Keeping  (2023-06-07 18:53:26.319758+00:00 - 2023-06-07 18:53:26.319758+00:00 -> 529.753 - 529.753)
  [297] Keeping  (2023-06-07

In [4]:
event_map = {'1': 11, '10': 10, '101': 101, '109': 109, '11': 11, '117': 117, '20': 20, '30': 30, '40': 40, '5': 5, '50': 50, '51': 51, '52': 52, '60': 60, '70': 70, '80': 80, '99999': 99999}

# get events and times
events, event_id = mne.events_from_annotations(raw_a, event_map)

e_a = events
# all rows with fixation (code 40)
e_40_a = e_a[e_a[:, 2] == 40]
# all rows with trial end (code 101)
e_101_a = e_a[e_a[:,2]==101]

a_tmin= e_40_a[0][0]/1000
a_tmax= e_101_a[-1][0]/1000

# Crop and make a copy and filter
filt_raw_a = raw_a.crop(tmin=a_tmin, tmax=a_tmax).copy().filter(l_freq=1.0, h_freq=40)

epochs_a = mne.Epochs(filt_raw_a, 
                    e_a, 
                    event_id=None, 
                    tmin=-0.2, 
                    tmax=0.5, 
                    preload=True, 
                    baseline=(None, 0))

Used Annotations descriptions: ['10', '101', '109', '117', '20', '30', '40', '50', '51', '52', '60', '70', '80', '99999']
Filtering raw data in 1 contiguous segment
Setting up band-pass filter from 1 - 40 Hz

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandpass filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower passband edge: 1.00
- Lower transition bandwidth: 1.00 Hz (-6 dB cutoff frequency: 0.50 Hz)
- Upper passband edge: 40.00 Hz
- Upper transition bandwidth: 10.00 Hz (-6 dB cutoff frequency: 45.00 Hz)
- Filter length: 3301 samples (3.301 s)



[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.1s remaining:    0.0s


Not setting metadata
415 matching events found
Setting baseline interval to [-0.2, 0.0] s
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 415 events and 701 original time points ...
6 bad epochs dropped


[Parallel(n_jobs=1)]: Done  63 out of  63 | elapsed:    0.8s finished


In [50]:
raw_a.plot()

Using pyopengl with version 3.1.6


Channels marked as bad:
none
Channels marked as bad:
none


In [5]:
# Fitting ICA
ica = ICA(n_components=len(filt_raw_a.ch_names)-1, max_iter="auto", random_state=999)
ica.fit(filt_raw_a)
ica

Fitting ICA to data using 63 channels (please be patient, this may take a while)
Selecting by number: 63 components
Fitting ICA took 38.1s.


<ICA | raw data decomposition, method: fastica (fit in 57 iterations on 703101 samples), 63 ICA components (63 PCA components available), channel types: eeg, no sources marked for exclusion>

In [ ]:
raw_a.load_data()
ica.plot_sources(raw_a)

Creating RawArray with float64 data, n_channels=63, n_times=703101
    Range : 40320 ... 743420 =     40.320 ...   743.420 secs
Ready.
Using qt as 2D backend.
Using pyopengl with version 3.1.6


    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
351 matching events found
No baseline correction applied
0 projection items activated
    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
351 matching events found
No baseline correction applied
0 projection items activated
    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
351 matching events found
No baseline correction applied
0 projection items activated
    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
351 matching events found
No baseline correction applied
0 projection items activated
    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
351 matching events found
No baseline correction applied
0 projection items activated


In [7]:
print(ica.exclude)

[0]


In [8]:
reconstr_raw = raw_a.copy()
# Apply ica to copy
ica.apply(reconstr_raw)
# Plot
raw_a.plot(title="Raw data")
reconstr_raw.plot(title="ICA applied")

Applying ICA to Raw instance
    Transforming to ICA space (63 components)
    Zeroing out 1 ICA component
    Projecting back using 63 PCA components
Using pyopengl with version 3.1.6
Using pyopengl with version 3.1.6


Channels marked as bad:
none
Channels marked as bad:
none


In [9]:
# Save file
file_name = session_id+'_'+posner_id+'.vhdr'
output_dir='cleaned'

print(file_name)
cur_dir = os.getcwd()
session_dir = os.path.join(cur_dir, output_dir, session_id)
print(session_dir)

if not os.path.exists(session_dir):
   os.makedirs(session_dir)

print("\n**** Saving file to: ", session_dir+'/'+file_name) 
mne.export.export_raw(session_dir+'/'+file_name, reconstr_raw, verbose=1)

m_15_01_pos1a.vhdr
/Users/babe/src/gla/dissertation/go/cleaned/m_15_01

**** Saving file to:  /Users/babe/src/gla/dissertation/go/cleaned/m_15_01/m_15_01_pos1a.vhdr


/Applications/MNE-Python/.mne-python/lib/python3.10/site-packages/pybv/_export.py:61: RuntimeWarning: Encountered data in 'short' format. Converting to float32.
  warn(
/Applications/MNE-Python/.mne-python/lib/python3.10/site-packages/pybv/io.py:690: UserWarning: Encountered unsupported non-voltage units: n/a
Note that the BrainVision format specification supports only µV.
  warn(msg)


In [10]:
!tree {session_dir}

/Users/babe/src/gla/dissertation/go/cleaned/m_15_01
├── m_15_01_pos1a.eeg
├── m_15_01_pos1a.vhdr
└── m_15_01_pos1a.vmrk

1 directory, 3 files


In [11]:
del raw_a
del reconstr_raw
del ica
del filt_raw_a

# Posner B

In [12]:
# Relabel stim events and load raw data
raw_b = relabel_events(session_id, posner_id_b)

Data file:  m_15_01/m_15_01_pos1b.vhdr


/Users/babe/src/gla/dissertation/go/rename_events.py:50: RuntimeWarning: No coordinate information found for channels ['ECG']. Setting channel types to misc. To avoid this warning, set channel types explicitly.
  raw = mne.io.read_raw_brainvision(vhdr_file, preload=True, verbose=0)


Used Annotations descriptions: ['New Segment/', 'Stimulus/S 10', 'Stimulus/S 20', 'Stimulus/S 30', 'Stimulus/S 40', 'Stimulus/S 50', 'Stimulus/S 51', 'Stimulus/S 60', 'Stimulus/S 70', 'Stimulus/S 80', 'Stimulus/S101', 'Stimulus/S109', 'Stimulus/S117']
Found '1a' in file: m_15_01/15_1a_posner_task_2023-06-07_18h43.06.180/15_1a_posner_task_2023-06-07_18h43.06.180.csv
Found '1b' in file: m_15_01/15_1b_posner_task_2023-06-07_19h41.14.289/15_1b_posner_task_2023-06-07_19h41.14.289.csv
********** 1b
Used Annotations descriptions: ['New Segment/', 'Stimulus/S 10', 'Stimulus/S 20', 'Stimulus/S 30', 'Stimulus/S 40', 'Stimulus/S 50', 'Stimulus/S 51', 'Stimulus/S 60', 'Stimulus/S 70', 'Stimulus/S 80', 'Stimulus/S101', 'Stimulus/S109', 'Stimulus/S117']
len(events) 415
len(validity) 100
# of stim events 100
[    0     0 99999]
[9144    0   10]
[13191     0    40]
[14692     0    60]
[17921     0    50]
[18021     0    51]
[19691     0    40]
[21191     0    70]
[23891     0    50]
[23991     0    51

/Users/babe/src/gla/dissertation/go/rename_events.py:50: RuntimeWarning: Not setting position of 1 misc channel found in montage:
['ECG']
Consider setting the channel types to be of EEG/sEEG/ECoG/DBS/fNIRS using inst.set_channel_types before calling inst.set_montage, or omit these channels when creating your montage.
  raw = mne.io.read_raw_brainvision(vhdr_file, preload=True, verbose=0)


  [259] Keeping  (2023-06-07 19:52:27.709668+00:00 - 2023-06-07 19:52:27.709668+00:00 -> 430.694 - 430.694)
  [260] Keeping  (2023-06-07 19:52:30.079668+00:00 - 2023-06-07 19:52:30.079668+00:00 -> 433.064 - 433.064)
  [261] Keeping  (2023-06-07 19:52:31.579668+00:00 - 2023-06-07 19:52:31.579668+00:00 -> 434.564 - 434.564)
  [262] Keeping  (2023-06-07 19:52:34.509668+00:00 - 2023-06-07 19:52:34.509668+00:00 -> 437.494 - 437.494)
  [263] Keeping  (2023-06-07 19:52:34.609668+00:00 - 2023-06-07 19:52:34.609668+00:00 -> 437.594 - 437.594)
  [264] Keeping  (2023-06-07 19:52:36.579668+00:00 - 2023-06-07 19:52:36.579668+00:00 -> 439.564 - 439.564)
  [265] Keeping  (2023-06-07 19:52:38.079668+00:00 - 2023-06-07 19:52:38.079668+00:00 -> 441.064 - 441.064)
  [266] Keeping  (2023-06-07 19:52:40.809668+00:00 - 2023-06-07 19:52:40.809668+00:00 -> 443.794 - 443.794)
  [267] Keeping  (2023-06-07 19:52:40.909668+00:00 - 2023-06-07 19:52:40.909668+00:00 -> 443.894 - 443.894)
  [268] Keeping  (2023-06-07

In [13]:
event_map = {'1': 11, '10': 10, '101': 101, '109': 109, '11': 11, '117': 117, '20': 20, '30': 30, '40': 40, '5': 5, '50': 50, '51': 51, '52': 52, '60': 60, '70': 70, '80': 80, '99999': 99999}

# get events and times
events_b, event_id_b = mne.events_from_annotations(raw_b, event_map)

e_b = events_b
# all rows with fixation (code 40)
e_40_b = e_b[e_b[:, 2] == 40]
# all rows with trial end (code 101)
e_101_b = e_b[e_b[:,2]==101]

b_tmin= e_40_b[0][0]/1000
b_tmax= e_101_b[-1][0]/1000

# Crop and make a copy and filter
filt_raw_b = raw_b.crop(tmin=b_tmin, tmax=b_tmax).copy().filter(l_freq=1.0, h_freq=40)

epochs_b = mne.Epochs(filt_raw_b, 
                    e_b, 
                    event_id=None, 
                    tmin=-0.2, 
                    tmax=0.5, 
                    preload=True, 
                    baseline=(None, 0))

Used Annotations descriptions: ['10', '101', '109', '117', '20', '30', '40', '50', '51', '52', '60', '70', '80', '99999']
Filtering raw data in 1 contiguous segment
Setting up band-pass filter from 1 - 40 Hz

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandpass filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower passband edge: 1.00
- Lower transition bandwidth: 1.00 Hz (-6 dB cutoff frequency: 0.50 Hz)
- Upper passband edge: 40.00 Hz
- Upper transition bandwidth: 10.00 Hz (-6 dB cutoff frequency: 45.00 Hz)
- Filter length: 3301 samples (3.301 s)



[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.1s remaining:    0.0s


Not setting metadata
415 matching events found
Setting baseline interval to [-0.2, 0.0] s
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 415 events and 701 original time points ...
6 bad epochs dropped


[Parallel(n_jobs=1)]: Done  63 out of  63 | elapsed:    0.7s finished


In [5]:
raw_b.plot()

Using qt as 2D backend.
Using pyopengl with version 3.1.6


Channels marked as bad:
none


In [14]:
# Fitting ICA
ica_b = ICA(n_components=len(filt_raw_b.ch_names)-1, max_iter="auto", random_state=999)
ica_b.fit(filt_raw_b, verbose='DEBUG')
ica_b

Fitting ICA to data using 63 channels (please be patient, this may take a while)
Selecting by number: 63 components


/Applications/MNE-Python/.mne-python/lib/python3.10/site-packages/sklearn/decomposition/_fastica.py:123: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  warnings.warn(


Cropping annotations 2023-06-07 19:45:30.206668+00:00 - 2023-06-07 19:56:35.918668+00:00
  [0] Keeping  (2023-06-07 19:45:30.206668+00:00 - 2023-06-07 19:45:30.206668+00:00 -> 13.191 - 13.191)
  [1] Keeping  (2023-06-07 19:45:31.707668+00:00 - 2023-06-07 19:45:31.707668+00:00 -> 14.692 - 14.692)
  [2] Keeping  (2023-06-07 19:45:34.936668+00:00 - 2023-06-07 19:45:34.936668+00:00 -> 17.921 - 17.921)
  [3] Keeping  (2023-06-07 19:45:35.036668+00:00 - 2023-06-07 19:45:35.036668+00:00 -> 18.021 - 18.021)
  [4] Keeping  (2023-06-07 19:45:36.706668+00:00 - 2023-06-07 19:45:36.706668+00:00 -> 19.691 - 19.691)
  [5] Keeping  (2023-06-07 19:45:38.206668+00:00 - 2023-06-07 19:45:38.206668+00:00 -> 21.191 - 21.191)
  [6] Keeping  (2023-06-07 19:45:40.906668+00:00 - 2023-06-07 19:45:40.906668+00:00 -> 23.891 - 23.891)
  [7] Keeping  (2023-06-07 19:45:41.006668+00:00 - 2023-06-07 19:45:41.006668+00:00 -> 23.991 - 23.991)
  [8] Keeping  (2023-06-07 19:45:43.206668+00:00 - 2023-06-07 19:45:43.206668+0

<ICA | raw data decomposition, method: fastica (fit in 1000 iterations on 665712 samples), 63 ICA components (63 PCA components available), channel types: eeg, no sources marked for exclusion>

In [ ]:
raw_b.load_data()
ica_b.plot_sources(raw_b)

Creating RawArray with float64 data, n_channels=63, n_times=665712
    Range : 13191 ... 678902 =     13.191 ...   678.902 secs
Ready.
Using pyopengl with version 3.1.6


    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
332 matching events found
No baseline correction applied
0 projection items activated
    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
332 matching events found
No baseline correction applied
0 projection items activated
    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
332 matching events found
No baseline correction applied
0 projection items activated
    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
332 matching events found
No baseline correction applied
0 projection items activated
    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
332 matching events found
No baseline correction applied
0 projection items activated
    Using multitaper spectrum estimation with 7 DPSS windows
Not setting metadata
332 matching events found
No baseline correction applied
0 projection items ac

In [16]:
ica_b.exclude

[5]

In [17]:
reconstr_raw_b = raw_b.copy()
# Apply ica to copy
ica_b.apply(reconstr_raw_b)
# Plot and compare
raw_b.plot(title="Raw data (posner b)")
reconstr_raw_b.plot(title="ICA applied (posner b)")

Applying ICA to Raw instance
    Transforming to ICA space (63 components)
    Zeroing out 1 ICA component
    Projecting back using 63 PCA components
Using pyopengl with version 3.1.6
Using pyopengl with version 3.1.6


Channels marked as bad:
none
Channels marked as bad:
none


In [18]:
# Save file
file_name_b = session_id+'_'+posner_id_b+'.vhdr'
output_dir_b='cleaned'
cur_dir = os.getcwd()
session_dir = os.path.join(cur_dir, output_dir_b, session_id)
if not os.path.exists(session_dir):
   os.makedirs(session_dir)

print("\n**** Saving file to: ", session_dir+'/'+file_name_b) 
mne.export.export_raw(session_dir+'/'+file_name_b, reconstr_raw_b, verbose=1)


**** Saving file to:  /Users/babe/src/gla/dissertation/go/cleaned/m_15_01/m_15_01_pos1b.vhdr


/Applications/MNE-Python/.mne-python/lib/python3.10/site-packages/pybv/_export.py:61: RuntimeWarning: Encountered data in 'short' format. Converting to float32.
  warn(
/Applications/MNE-Python/.mne-python/lib/python3.10/site-packages/pybv/io.py:690: UserWarning: Encountered unsupported non-voltage units: n/a
Note that the BrainVision format specification supports only µV.
  warn(msg)


In [19]:
!tree {session_dir}

/Users/babe/src/gla/dissertation/go/cleaned/m_15_01
├── m_15_01_pos1a.eeg
├── m_15_01_pos1a.vhdr
├── m_15_01_pos1a.vmrk
├── m_15_01_pos1b.eeg
├── m_15_01_pos1b.vhdr
└── m_15_01_pos1b.vmrk

1 directory, 6 files


# ...

In [20]:
del raw_b
del reconstr_raw_b
del ica_b
del filt_raw_b